title: Dinosaurs Are Forever
description: code, music, creation
meta_description: "The Personal Blog of Chris J Arges"

baseurl: ""
url: "http://chrisarges.net"
github_username:  arges

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: chrisarges-net
google_analytics: UA-36012839-2
