name: Dinosaurs Are Forever
description: code, music, creation
meta_description: "The Personal Blog of Chris J Arges"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://chrisarges.net'
google_analytics: 'UA-36012839-2'

# Details for the RSS feed generator
url:            'http://chrisarges.net'
author:         'Chris J Arges'

gems:
  - jekyll-sitemap
